name: "JSON test results reporter to Slack"
description: "Send JSON test results to any slack channel"
branding:
  icon: 'upload'
  color: 'purple'
inputs:
  title:
    description: "Title of the test result which will appear in slack message"
    required: false
  url:
    description: "URL of the test result which will appear in slack message"
    required: false
  slack-bot-token:
    description: "Token of Slack bot configured"
    required: true
  slack-channel:
    description: "Channel name to post the message"
    required: true
  json-path:
    description: "Filepath of json file from the root directory"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"